export interface KeywordInfo {
  keyword: string;
  volume: string;
  kd: string;
  intent: string;
}

export const SEO_KEYWORDS_REGISTRY: Record<string, KeywordInfo[]> = {
  "spin-renaissance-t20-cricket-analysis": [
    { keyword: "how to bowl quick leg spin", volume: "850/mo", kd: "12%", intent: "Informational" },
    { keyword: "rashid khan bowling grip style", volume: "950/mo", kd: "14%", intent: "Informational" },
    { keyword: "wrist spin coaching guide easy", volume: "450/mo", kd: "9%", intent: "Commercial" },
    { keyword: "magnus effect cricket ball deviation", volume: "350/mo", kd: "8%", intent: "Informational" },
    { keyword: "t20 powerplay bowling strategies", volume: "550/mo", kd: "11%", intent: "Investigational" },
    { keyword: "leg break bowling release height", volume: "300/mo", kd: "7%", intent: "Informational" },
    { keyword: "increase spinner ball rotation rpm", volume: "400/mo", kd: "6%", intent: "Informational" },
    { keyword: "how to read google cricket scores", volume: "2100/mo", kd: "18%", intent: "Navigational" },
    { keyword: "under cut googly release mechanics", volume: "250/mo", kd: "5%", intent: "Informational" },
    { keyword: "fast spinner vs slow spinner leg break", volume: "350/mo", kd: "12%", intent: "Investigational" },
    { keyword: "spin bowling shoulder injury prevention", volume: "700/mo", kd: "15%", intent: "Informational" },
    { keyword: "cricket ball drift angle physics", volume: "200/mo", kd: "4%", intent: "Informational" },
    { keyword: "t20 cricket ball swing humidity", volume: "600/mo", kd: "13%", intent: "Informational" },
    { keyword: "bat sweet spot rebound dynamics", volume: "300/mo", kd: "8%", intent: "Informational" },
    { keyword: "low bounce pitch cricket tactics", volume: "450/mo", kd: "11%", intent: "Investigational" },
    { keyword: "legspin wrist extension angle", volume: "150/mo", kd: "3%", intent: "Informational" },
    { keyword: "how to play back of hand googly", volume: "800/mo", kd: "16%", intent: "Informational" },
    { keyword: "cricket wrist flexor workouts", volume: "500/mo", kd: "10%", intent: "Commercial" },
    { keyword: "wickets in powerplay statistical correlation", volume: "180/mo", kd: "2%", intent: "Informational" },
    { keyword: "spin bowler run up acceleration", volume: "320/mo", kd: "8%", intent: "Informational" },
    { keyword: "best cricket spikes for spin bowlers", volume: "1100/mo", kd: "19%", intent: "Commercial" },
    { keyword: "how cricket editors update score manually", volume: "140/mo", kd: "4%", intent: "Informational" },
    { keyword: "icc rankings bowler equation math", volume: "350/mo", kd: "12%", intent: "Informational" },
    { keyword: "wrist spinner versus left handed batter", volume: "280/mo", kd: "6%", intent: "Investigational" },
    { keyword: "cricket ball seam position wind drift", volume: "190/mo", kd: "5%", intent: "Informational" },
    { keyword: "how to spot a googly early", volume: "650/mo", kd: "14%", intent: "Informational" },
    { keyword: "wrist flex joint strength cricket", volume: "300/mo", kd: "9%", intent: "Commercial" },
    { keyword: "leg break wrist roll action tutorial", volume: "400/mo", kd: "11%", intent: "Informational" },
    { keyword: "cricket analyst telemetry software", volume: "250/mo", kd: "13%", intent: "Commercial" },
    { keyword: "babar azam cover drive kinetic chain", volume: "750/mo", kd: "15%", intent: "Informational" },
    { keyword: "wrist spinners in modern T20 league", volume: "550/mo", kd: "12%", intent: "Informational" },
    { keyword: "how to bowl top spinner clean", volume: "480/mo", kd: "10%", intent: "Informational" },
    { keyword: "cricket pitch dust wear spin impact", volume: "220/mo", kd: "6%", intent: "Informational" },
    { keyword: "wicketkeepers role in reading spinner googly", volume: "170/mo", kd: "3%", intent: "Informational" },
    { keyword: "cricket leather ball RPM test metrics", volume: "120/mo", kd: "2%", intent: "Informational" },
    { keyword: "how to increase ball dip spinner", volume: "300/mo", kd: "7%", intent: "Informational" },
    { keyword: "unorthodox cricket action leg break", volume: "320/mo", kd: "9%", intent: "Informational" },
    { keyword: "wrist spin versus off spin difference", volume: "850/mo", kd: "17%", intent: "Informational" },
    { keyword: "best wrist spinner of this decade list", volume: "550/mo", kd: "15%", intent: "Investigational" },
    { keyword: "cricket biomechanics speed release research", volume: "190/mo", kd: "5%", intent: "Informational" },
    { keyword: "wrist rotation exercises cricket", volume: "620/mo", kd: "11%", intent: "Commercial" },
    { keyword: "googly legbreak combo bowling practice", volume: "240/mo", kd: "6%", intent: "Informational" },
    { keyword: "t20 powerplay field setup ideas", volume: "680/mo", kd: "13%", intent: "Investigational" },
    { keyword: "middle over wickets importance white ball", volume: "140/mo", kd: "4%", intent: "Informational" },
    { keyword: "cricket ball spin rates tracker", volume: "250/mo", kd: "12%", intent: "Commercial" },
    { keyword: "front arm pull spin bowling power", volume: "180/mo", kd: "3%", intent: "Informational" },
    { keyword: "back foot pivot leg spin bowler", volume: "210/mo", kd: "5%", intent: "Informational" },
    { keyword: "how to stop full toss leg spinner", volume: "410/mo", kd: "8%", intent: "Informational" },
    { keyword: "cricket dynamic balance delivery stride", volume: "150/mo", kd: "4%", intent: "Informational" },
    { keyword: "best leather balls for spin bowling practice", volume: "750/mo", kd: "18%", intent: "Commercial" }
  ],
  "tactical-extinction-classical-fullbacks-inverted-pivot": [
    { keyword: "how does inverted fullback position work", volume: "1250/mo", kd: "14%", intent: "Informational" },
    { keyword: "inverted wing back vs classical fullback", volume: "950/mo", kd: "11%", intent: "Informational" },
    { keyword: "pep guardiola fullback midfield transition", volume: "680/mo", kd: "13%", intent: "Informational" },
    { keyword: "rest defense positioning tactics soccer", volume: "450/mo", kd: "9%", intent: "Informational" },
    { keyword: "prevent soccer counter attack center lane", volume: "320/mo", kd: "7%", intent: "Informational" },
    { keyword: "john stones playmaking defense details", volume: "410/mo", kd: "8%", intent: "Informational" },
    { keyword: "soccer training scanning frequency tips", volume: "550/mo", kd: "10%", intent: "Commercial" },
    { keyword: "midfielder spatial awareness exercises", volume: "620/mo", kd: "12%", intent: "Commercial" },
    { keyword: "how to defend overlaps soccer formations", volume: "750/mo", kd: "16%", intent: "Informational" },
    { keyword: "left back transitions to defensive midfield", volume: "280/mo", kd: "6%", intent: "Informational" },
    { keyword: "dual pivot soccer construct advantages", volume: "350/mo", kd: "9%", intent: "Informational" },
    { keyword: "tactical system 3223 formation depth", volume: "520/mo", kd: "11%", intent: "Informational" },
    { keyword: "rest defense block structure diagrams", volume: "420/mo", kd: "8%", intent: "Informational" },
    { keyword: "prevent wing runs full back stance", volume: "330/mo", kd: "7%", intent: "Informational" },
    { keyword: "trent alexander arnold midfield stats", volume: "1150/mo", kd: "18%", intent: "Navigational" },
    { keyword: "inverted fullback tactical guidelines easy", volume: "310/mo", kd: "5%", intent: "Informational" },
    { keyword: "soccer overlapping fb physical stamina", volume: "490/mo", kd: "10%", intent: "Informational" },
    { keyword: "why classical fullback is extinct", volume: "720/mo", kd: "15%", intent: "Informational" },
    { keyword: "progressive passes left back metrics", volume: "210/mo", kd: "4%", intent: "Informational" },
    { keyword: "soccer high press angle restrictions", volume: "380/mo", kd: "9%", intent: "Informational" },
    { keyword: "rest defense box mechanics tutorial", volume: "190/mo", kd: "5%", intent: "Informational" },
    { keyword: "how to coach inverted fullback juniors", volume: "270/mo", kd: "8%", intent: "Commercial" },
    { keyword: "soccer field lateral five channel map", volume: "150/mo", kd: "3%", intent: "Informational" },
    { keyword: "midfield numerical superiority statistical value", volume: "130/mo", kd: "2%", intent: "Informational" },
    { keyword: "left mid versus central midfield space", volume: "410/mo", kd: "9%", intent: "Informational" },
    { keyword: "tactical division of pitch half spaces", volume: "380/mo", kd: "11%", intent: "Informational" },
    { keyword: "centerback diagonal passing angles", volume: "230/mo", kd: "6%", intent: "Informational" },
    { keyword: "ball recovery rate in final third", volume: "260/mo", kd: "7%", intent: "Informational" },
    { keyword: "back four alignment vs back three soccer", volume: "850/mo", kd: "16%", intent: "Informational" },
    { keyword: "inverted fb defensive recovery velocity", volume: "180/mo", kd: "5%", intent: "Informational" },
    { keyword: "counterpressing transition distance optimization", volume: "140/mo", kd: "4%", intent: "Informational" },
    { keyword: "soccer scouting reports spatial memory test", volume: "220/mo", kd: "8%", intent: "Commercial" },
    { keyword: "best cleats for technical soccer defenders", volume: "980/mo", kd: "17%", intent: "Commercial" },
    { keyword: "how to block low block crosses", volume: "460/mo", kd: "10%", intent: "Informational" },
    { keyword: "inverted pivot full back coaching lessons", volume: "250/mo", kd: "9%", intent: "Commercial" },
    { keyword: "soccer defensive block compactness index", volume: "120/mo", kd: "3%", intent: "Informational" },
    { keyword: "leftback inverted overlapping runs soccer", volume: "290/mo", kd: "8%", intent: "Informational" },
    { keyword: "soccer build up phases defense positioning", volume: "510/mo", kd: "13%", intent: "Informational" },
    { keyword: "tactical board apps for football coaches", volume: "850/mo", kd: "15%", intent: "Commercial" },
    { keyword: "football tactical analysis blogs free", volume: "620/mo", kd: "11%", intent: "Informational" },
    { keyword: "rest defense structure versus counters", volume: "310/mo", kd: "6%", intent: "Informational" },
    { keyword: "how to beat five block structure soccer", volume: "260/mo", kd: "9%", intent: "Informational" },
    { keyword: "inverted fullback tracking speed test", volume: "140/mo", kd: "4%", intent: "Informational" },
    { keyword: "midfielder over the shoulder scan frequency", volume: "190/mo", kd: "5%", intent: "Informational" },
    { keyword: "football dynamic spacing calculations", volume: "110/mo", kd: "2%", intent: "Informational" },
    { keyword: "defending inverted wingers tips right back", volume: "490/mo", kd: "12%", intent: "Informational" },
    { keyword: "fullback back tracking physical threshold", volume: "210/mo", kd: "7%", intent: "Informational" },
    { keyword: "soccer telemetry analytics team setups", volume: "230/mo", kd: "11%", intent: "Commercial" },
    { keyword: "inverted playmaker fullback transition rules", volume: "170/mo", kd: "6%", intent: "Informational" },
    { keyword: "tactical playbooks defensive transitions modern", volume: "390/mo", kd: "10%", intent: "Commercial" }
  ],
  "analytical-obsession-nba-midrange-efficiency": [
    { keyword: "midrange shot expected points value nba", volume: "750/mo", kd: "11%", intent: "Informational" },
    { keyword: "is the mid range jumper dead math", volume: "850/mo", kd: "13%", intent: "Informational" },
    { keyword: "nba analytics shot chart expected points", volume: "620/mo", kd: "14%", intent: "Informational" },
    { keyword: "corner three point efficiency statistics", volume: "510/mo", kd: "9%", intent: "Informational" },
    { keyword: "why are layup percentage so high", volume: "390/mo", kd: "7%", intent: "Informational" },
    { keyword: "five out offense nba plays diagrams", volume: "680/mo", kd: "15%", intent: "Informational" },
    { keyword: "gravitational pull in basketball space", volume: "220/mo", kd: "5%", intent: "Informational" },
    { keyword: "nba mid range shooting drill routines", volume: "550/mo", kd: "12%", intent: "Commercial" },
    { keyword: "basketball shot selection percentage metrics", volume: "430/mo", kd: "10%", intent: "Informational" },
    { keyword: "high efficiency layups expected scoring", volume: "180/mo", kd: "4%", intent: "Informational" },
    { keyword: "nba catch and shoot corners efficiency", volume: "330/mo", kd: "8%", intent: "Informational" },
    { keyword: "how to calculate shot value basketball", volume: "220/mo", kd: "6%", intent: "Informational" },
    { keyword: "turnaround jump shot balance training", volume: "410/mo", kd: "9%", intent: "Commercial" },
    { keyword: "victor wembanyama shot zone analytics", volume: "950/mo", kd: "17%", intent: "Navigational" },
    { keyword: "michael jordan midrange consistency secret", volume: "850/mo", kd: "16%", intent: "Informational" },
    { keyword: "basketball floor spacing metrics", volume: "290/mo", kd: "7%", intent: "Informational" },
    { keyword: "nba playoff defensive mid range strategies", volume: "310/mo", kd: "11%", intent: "Informational" },
    { keyword: "three point shooting mathematically superior", volume: "420/mo", kd: "10%", intent: "Informational" },
    { keyword: "basketball analytical obsession statistics", volume: "150/mo", kd: "4%", intent: "Informational" },
    { keyword: "expected points per shot nba calculator", volume: "140/mo", kd: "3%", intent: "Informational" },
    { keyword: "dunks vs layups efficiency stats", volume: "280/mo", kd: "6%", intent: "Informational" },
    { keyword: "best basketball shooting apps analyzer", volume: "750/mo", kd: "18%", intent: "Commercial" },
    { keyword: "nba draft analytical screening value", volume: "190/mo", kd: "8%", intent: "Informational" },
    { keyword: "spacing index calculation basketball", volume: "110/mo", kd: "2%", intent: "Informational" },
    { keyword: "how to draw defenders out paint", volume: "360/mo", kd: "7%", intent: "Informational" },
    { keyword: "basketball coaching court positioning maps", volume: "490/mo", kd: "12%", intent: "Commercial" },
    { keyword: "midrange fadeaway mechanical steps easy", volume: "320/mo", kd: "9%", intent: "Informational" },
    { keyword: "how shooting guards improve launch speed", volume: "260/mo", kd: "8%", intent: "Informational" },
    { keyword: "above the break 3 efficiency nba", volume: "210/mo", kd: "5%", intent: "Informational" },
    { keyword: "nba regular season court maps telemetry", volume: "170/mo", kd: "6%", intent: "Informational" },
    { keyword: "statistical graveyard shot locations nba", volume: "135/mo", kd: "4%", intent: "Informational" },
    { keyword: "offensive ball movement metrics analytics", volume: "240/mo", kd: "8%", intent: "Informational" },
    { keyword: "best tracking sensors for basketball trainers", volume: "550/mo", kd: "14%", intent: "Commercial" },
    { keyword: "basketball court space gravity models", volume: "160/mo", kd: "5%", intent: "Informational" },
    { keyword: "offensive efficiency metrics team stats", volume: "380/mo", kd: "12%", intent: "Informational" },
    { keyword: "nba post season mid range utility", volume: "200/mo", kd: "8%", intent: "Informational" },
    { keyword: "how to shoot 50 percent midrange", volume: "290/mo", kd: "7%", intent: "Informational" },
    { keyword: "basketball shot contest distance measurement", volume: "110/mo", kd: "3%", intent: "Informational" },
    { keyword: "three pointer expected return mathematical proofs", volume: "90/mo", kd: "2%", intent: "Informational" },
    { keyword: "nba statistics tracking cameras in stadiums", volume: "410/mo", kd: "11%", intent: "Informational" },
    { keyword: "basketball dynamic movement training drills", volume: "620/mo", kd: "13%", intent: "Commercial" },
    { keyword: "shooting coach training certificate online", volume: "350/mo", kd: "15%", intent: "Commercial" },
    { keyword: "how to get open corner spots", volume: "480/mo", kd: "10%", intent: "Informational" },
    { keyword: "basketball paint touches to shots ratio", volume: "130/mo", kd: "4%", intent: "Informational" },
    { keyword: "expected value shot selectors nba", volume: "160/mo", kd: "6%", intent: "Informational" },
    { keyword: "free throw percentage expected value model", volume: "190/mo", kd: "5%", intent: "Informational" },
    { keyword: "basketball ankle and hip deceleration strength", volume: "310/mo", kd: "9%", intent: "Informational" },
    { keyword: "best basketball shooting sleeves comparison", volume: "680/mo", kd: "16%", intent: "Commercial" },
    { keyword: "basketball half court offensive setups simple", volume: "440/mo", kd: "11%", intent: "Informational" },
    { keyword: "expected value basketball stat index", volume: "125/mo", kd: "4%", intent: "Informational" }
  ],
  "aerodynamics-f1-ground-effect-engineering-upgrades": [
    { keyword: "how does f1 ground effect work", volume: "2150/mo", kd: "15%", intent: "Informational" },
    { keyword: "f1 venturi tunnel profiles side view", volume: "850/mo", kd: "11%", intent: "Informational" },
    { keyword: "formula 1 porpoising physics explaining", volume: "950/mo", kd: "13%", intent: "Informational" },
    { keyword: "flexible floor plies carbon engineering f1", volume: "410/mo", kd: "9%", intent: "Informational" },
    { keyword: "formula 1 mechanical dampers roll control", volume: "350/mo", kd: "8%", intent: "Informational" },
    { keyword: "downforce generation undertray vs wing", volume: "550/mo", kd: "12%", intent: "Informational" },
    { keyword: "f1 wind tunnel calibration errors", volume: "280/mo", kd: "6%", intent: "Informational" },
    { keyword: "aerodynamic drag reduction sidepod channels", volume: "310/mo", kd: "8%", intent: "Informational" },
    { keyword: "carbon floor flexing legal limit f1", volume: "490/mo", kd: "12%", intent: "Informational" },
    { keyword: "f1 ride height dynamic test metrics", volume: "220/mo", kd: "5%", intent: "Informational" },
    { keyword: "venturi throat low pressure dynamics f1", volume: "180/mo", kd: "4%", intent: "Informational" },
    { keyword: "f1 downforce stall points calculations", volume: "190/mo", kd: "6%", intent: "Informational" },
    { keyword: "mechanical heave dampers formula 1 physics", volume: "240/mo", kd: "7%", intent: "Informational" },
    { keyword: "f1 aerodynamist telemetry data packages", volume: "130/mo", kd: "3%", intent: "Commercial" },
    { keyword: "how to calculate downforce f1 car", volume: "450/mo", kd: "10%", intent: "Informational" },
    { keyword: "underfloor suction vacuum boundary seal", volume: "210/mo", kd: "7%", intent: "Informational" },
    { keyword: "front wing trailing vortices clean air", volume: "330/mo", kd: "9%", intent: "Informational" },
    { keyword: "f1 tyre heat transfer telemetry", volume: "620/mo", kd: "14%", intent: "Informational" },
    { keyword: "ground effect venturi design tutorials easy", volume: "250/mo", kd: "8%", intent: "Commercial" },
    { keyword: "flexible front wing f1 regulations", volume: "750/mo", kd: "16%", intent: "Informational" },
    { keyword: "f1 constructors technical upgrades tracker", volume: "850/mo", kd: "15%", intent: "Navigational" },
    { keyword: "carbon fiber ply pre stress f1", volume: "160/mo", kd: "4%", intent: "Informational" },
    { keyword: "f1 simulator driver correlation studies", volume: "310/mo", kd: "11%", intent: "Informational" },
    { keyword: "computational fluid dynamics f1 open source", volume: "680/mo", kd: "13%", intent: "Commercial" },
    { keyword: "f1 car floor wear skid block regulations", volume: "400/mo", kd: "10%", intent: "Informational" },
    { keyword: "how drag coefficient changes with wind", volume: "180/mo", kd: "5%", intent: "Informational" },
    { keyword: "sidepod air intake vortex generator f1", volume: "270/mo", kd: "9%", intent: "Informational" },
    { keyword: "f1 mechanical yaw pitch roll sensors", volume: "140/mo", kd: "4%", intent: "Commercial" },
    { keyword: "how f1 teams test tire thermal degradation", volume: "210/mo", kd: "6%", intent: "Informational" },
    { keyword: "active vs passive suspension physics f1", volume: "510/mo", kd: "12%", intent: "Informational" },
    { keyword: "F1 2026 engine regulation specs clean", volume: "950/mo", kd: "18%", intent: "Navigational" },
    { keyword: "f1 aerodynamics job entry requirements", volume: "750/mo", kd: "14%", intent: "Commercial" },
    { keyword: "how to buy used f1 carbon parts", volume: "520/mo", kd: "17%", intent: "Commercial" },
    { keyword: "f1 aerodynamic upgrades wind tunnel time", volume: "290/mo", kd: "8%", intent: "Informational" },
    { keyword: "ground effect ride height window mm", volume: "110/mo", kd: "2%", intent: "Informational" },
    { keyword: "downforce loss following car percentage f1", volume: "380/mo", kd: "13%", intent: "Informational" },
    { keyword: "best model scale wind tunnels engineering", volume: "420/mo", kd: "15%", intent: "Commercial" },
    { keyword: "f1 steering wheel sensor readout screen", volume: "230/mo", kd: "9%", intent: "Informational" },
    { keyword: "monaco gp low speed downforce settings", volume: "310/mo", kd: "7%", intent: "Informational" },
    { keyword: "dry carbon fiber prepreg autoclaves cost", volume: "190/mo", kd: "6%", intent: "Commercial" },
    { keyword: "how to build aerodynamics model plane", volume: "680/mo", kd: "14%", intent: "Commercial" },
    { keyword: "undertray diffuser angle downforce formula", volume: "150/mo", kd: "5%", intent: "Informational" },
    { keyword: "tire friction coefficients thermal limits f1", volume: "120/mo", kd: "3%", intent: "Informational" },
    { keyword: "f1 downforce simulation apps android", volume: "240/mo", kd: "10%", intent: "Commercial" },
    { keyword: "formula one technical reports download free", volume: "350/mo", kd: "8%", intent: "Informational" },
    { keyword: "bernoulli principle race car downforce", volume: "510/mo", kd: "11%", intent: "Informational" },
    { keyword: "formula 1 active aerodynamic changes spec", volume: "420/mo", kd: "13%", intent: "Informational" },
    { keyword: "f1 boundary layer separation airflow", volume: "170/mo", kd: "5%", intent: "Informational" },
    { keyword: "constructors points mathematically secure equation", volume: "110/mo", kd: "3%", intent: "Informational" },
    { keyword: "best wind tunnel software student free", volume: "490/mo", kd: "12%", intent: "Commercial" }
  ],
  "esports-franchise-economics-paradox-valuations": [
    { keyword: "esports franchise financial crash review", volume: "650/mo", kd: "11%", intent: "Informational" },
    { keyword: "how do esports teams make profit", volume: "850/mo", kd: "13%", intent: "Informational" },
    { keyword: "twitch co streaming revenue sharing specs", volume: "510/mo", kd: "9%", intent: "Informational" },
    { keyword: "in game cosmetics revenue share teams", volume: "380/mo", kd: "8%", intent: "Informational" },
    { keyword: "riot games team skin system economics", volume: "490/mo", kd: "12%", intent: "Informational" },
    { keyword: "esports local ticket sales stadium limits", volume: "210/mo", kd: "6%", intent: "Informational" },
    { keyword: "twitch vs youtube gaming broadcaster fees", volume: "750/mo", kd: "14%", intent: "Investigational" },
    { keyword: "esports sponsorship average deal cost", volume: "320/mo", kd: "10%", intent: "Commercial" },
    { keyword: "cheap gaming house operation expense plans", volume: "240/mo", kd: "7%", intent: "Commercial" },
    { keyword: "esports fan average revenue per user", volume: "290/mo", kd: "11%", intent: "Informational" },
    { keyword: "why esports franchise spots are bubble", volume: "430/mo", kd: "12%", intent: "Informational" },
    { keyword: "closed loop esports leagues advantages", volume: "180/mo", kd: "5%", intent: "Informational" },
    { keyword: "game developer licensing system esports", volume: "220/mo", kd: "8%", intent: "Informational" },
    { keyword: "gaming tournament prize split calculator", volume: "590/mo", kd: "15%", intent: "Commercial" },
    { keyword: "lol esports team skin purchase rate", volume: "310/mo", kd: "9%", intent: "Informational" },
    { keyword: "valorant champion bundle revenue shares", volume: "950/mo", kd: "17%", intent: "Navigational" },
    { keyword: "traditional sports owner buying esports team", volume: "190/mo", kd: "6%", intent: "Informational" },
    { keyword: "geographic fan base dispersion gaming", volume: "130/mo", kd: "3%", intent: "Informational" },
    { keyword: "esports team merch shop margin details", volume: "330/mo", kd: "10%", intent: "Commercial" },
    { keyword: "gaming team custom emotes twitch rate", volume: "410/mo", kd: "7%", intent: "Informational" },
    { keyword: "is esports dying in 2026 stats", volume: "1250/mo", kd: "19%", intent: "Informational" },
    { keyword: "how much esports coach salary cost", volume: "850/mo", kd: "16%", intent: "Commercial" },
    { keyword: "esports remote production setups cheap", volume: "210/mo", kd: "8%", intent: "Commercial" },
    { keyword: "gaming streamer co stream agreement templates", volume: "150/mo", kd: "11%", intent: "Commercial" },
    { keyword: "riot games vct partner team benefits", volume: "550/mo", kd: "14%", intent: "Navigational" },
    { keyword: "esports player transfer pool fee matrix", volume: "140/mo", kd: "5%", intent: "Informational" },
    { keyword: "digital item licensing deals game studio", volume: "250/mo", kd: "13%", intent: "Commercial" },
    { keyword: "twitch chat sub income distribution teams", volume: "320/mo", kd: "9%", intent: "Informational" },
    { keyword: "sustainable gaming organization budget tools", volume: "180/mo", kd: "12%", intent: "Commercial" },
    { keyword: "intellectual property ownership esports devs", volume: "160/mo", kd: "7%", intent: "Informational" },
    { keyword: "esports business course online cost", volume: "450/mo", kd: "15%", intent: "Commercial" },
    { keyword: "gaming hardware sponsor payout benchmarks", volume: "290/mo", kd: "13%", intent: "Commercial" },
    { keyword: "average esports views on youtube platform", volume: "620/mo", kd: "11%", intent: "Informational" },
    { keyword: "how to pitches esports teams to brands", volume: "380/mo", kd: "14%", intent: "Commercial" },
    { keyword: "gaming tournament ticket system integration", volume: "230/mo", kd: "10%", intent: "Commercial" },
    { keyword: "cheap custom esport jerseys low minimums", volume: "1150/mo", kd: "18%", intent: "Commercial" },
    { keyword: "esports financial reporting template free", volume: "170/mo", kd: "5%", intent: "Commercial" },
    { keyword: "vct skin bundles total revenue 2025", volume: "750/mo", kd: "15%", intent: "Navigational" },
    { keyword: "league of legends team salary caps rule", volume: "440/mo", kd: "12%", intent: "Informational" },
    { keyword: "esports agency contract review fees", volume: "390/mo", kd: "14%", intent: "Commercial" },
    { keyword: "gaming streamer roster contract templates", volume: "280/mo", kd: "11%", intent: "Commercial" },
    { keyword: "digital fans monetizations strategies list", volume: "190/mo", kd: "8%", intent: "Informational" },
    { keyword: "esports audience demographics analytics breakdown", volume: "350/mo", kd: "9%", intent: "Informational" },
    { keyword: "riot games local regional servers cost", volume: "210/mo", kd: "6%", intent: "Informational" },
    { keyword: "valorant gaming setups team house specs", volume: "490/mo", kd: "13%", intent: "Informational" },
    { keyword: "streamer desk telemetry overlay setup", volume: "310/mo", kd: "12%", intent: "Commercial" },
    { keyword: "how to host local gaming bracket lan", volume: "680/mo", kd: "11%", intent: "Informational" },
    { keyword: "best esports contract lawyers hourly rate", volume: "240/mo", kd: "16%", intent: "Commercial" },
    { keyword: "closed league expansion slot evaluations", volume: "130/mo", kd: "7%", intent: "Informational" },
    { keyword: "esports venture capitalist investment pitches", volume: "160/mo", kd: "13%", intent: "Commercial" }
  ],
  "science-lateral-tennis-footwork-clay-sliding": [
    { keyword: "clay court tennis sliding physics", volume: "750/mo", kd: "13%", intent: "Informational" },
    { keyword: "roland garros court dirt sliding steps", volume: "550/mo", kd: "11%", intent: "Informational" },
    { keyword: "lateral thigh lunges tennis workout routines", volume: "620/mo", kd: "12%", intent: "Commercial" },
    { keyword: "clay tennis shoe outsole grip pattern", volume: "850/mo", kd: "15%", intent: "Commercial" },
    { keyword: "prevent clay slide tennis joint injuries", volume: "390/mo", kd: "9%", intent: "Informational" },
    { keyword: "atp player clay slide speed deceleration", volume: "280/mo", kd: "8%", intent: "Informational" },
    { keyword: "elastic kinetic chain tennis movement drills", volume: "420/mo", kd: "10%", intent: "Commercial" },
    { keyword: "clay court friction coefficient dynamics", volume: "180/mo", kd: "5%", intent: "Informational" },
    { keyword: "hip mobility lateral coverage exercises ATP", volume: "490/mo", kd: "11%", intent: "Commercial" },
    { keyword: "tennis court sliding on hardcourt vs clay", volume: "650/mo", kd: "14%", intent: "Informational" },
    { keyword: "adductor muscle strength workouts tennis", volume: "510/mo", kd: "10%", intent: "Commercial" },
    { keyword: "how to decrease slide stop time tennis", volume: "320/mo", kd: "7%", intent: "Informational" },
    { keyword: "clay court tennis socks red stain washing", volume: "1150/mo", kd: "18%", intent: "Informational" },
    { keyword: "unilateral knee joint loading tennis players", volume: "140/mo", kd: "4%", intent: "Informational" },
    { keyword: "roland garros brick dust mix specification", volume: "220/mo", kd: "6%", intent: "Informational" },
    { keyword: "atp players who slide on hard courts", volume: "950/mo", kd: "16%", intent: "Navigational" },
    { keyword: "clay court tennis sliding drills for kids", volume: "330/mo", kd: "9%", intent: "Commercial" },
    { keyword: "body weight shift during tennis forehand", volume: "410/mo", kd: "11%", intent: "Informational" },
    { keyword: "best clay tennis shoes online reviews", volume: "1250/mo", kd: "19%", intent: "Commercial" },
    { keyword: "how to pivot foot when hitting backhand", volume: "310/mo", kd: "8%", intent: "Informational" },
    { keyword: "ankles sprain prevention clay court tennis", volume: "680/mo", kd: "14%", intent: "Informational" },
    { keyword: "tennis baseline lateral deceleration stats", volume: "130/mo", kd: "5%", intent: "Informational" },
    { keyword: "composite tennis rackets damp vibrations", volume: "450/mo", kd: "12%", intent: "Commercial" },
    { keyword: "tennis court surface impact on speed", volume: "380/mo", kd: "9%", intent: "Informational" },
    { keyword: "how to train muscles for tennis footwork", volume: "550/mo", kd: "11%", intent: "Commercial" },
    { keyword: "prevent tendonitis knee court sliding", volume: "490/mo", kd: "10%", intent: "Informational" },
    { keyword: "tennis sliding technique step by step", volume: "850/mo", kd: "13%", intent: "Informational" },
    { keyword: "hip external rotator dynamic stretches", volume: "440/mo", kd: "9%", intent: "Commercial" },
    { keyword: "tennis movement analyst sensor wear", volume: "190/mo", kd: "7%", intent: "Commercial" },
    { keyword: "atp tour clay swing schedule list", volume: "750/mo", kd: "15%", intent: "Navigational" },
    { keyword: "clay court tennis maintenance brush tools", volume: "310/mo", kd: "8%", intent: "Commercial" },
    { keyword: "how to construct clay tennis court home", volume: "520/mo", kd: "17%", intent: "Commercial" },
    { keyword: "atp speed tracking live data telemetry", volume: "250/mo", kd: "13%", intent: "Informational" },
    { keyword: "clay court slide deceleration G force", volume: "110/mo", kd: "3%", intent: "Informational" },
    { keyword: "lower spine torque during clay sliding", volume: "150/mo", kd: "4%", intent: "Informational" },
    { keyword: "adductor strain healing time athletes", volume: "620/mo", kd: "11%", intent: "Informational" },
    { keyword: "plyometric workouts for lateral agility tennis", volume: "580/mo", kd: "12%", intent: "Commercial" },
    { keyword: "best tennis shoes for sliding clay courts", volume: "1100/mo", kd: "15%", intent: "Commercial" },
    { keyword: "how much red clay for tennis court", volume: "290/mo", kd: "10%", intent: "Commercial" },
    { keyword: "tennis slide foot angle mechanics diagrams", volume: "160/mo", kd: "6%", intent: "Informational" },
    { keyword: "atp player sliding on grass surface physics", volume: "210/mo", kd: "8%", intent: "Informational" },
    { keyword: "improve court recovery time agility runs", volume: "480/mo", kd: "10%", intent: "Commercial" },
    { keyword: "tennis baseline coverage kinetic efficiency formulas", volume: "120/mo", kd: "4%", intent: "Informational" },
    { keyword: "leg muscle workouts for tennis players", volume: "620/mo", kd: "12%", intent: "Commercial" },
    { keyword: "ankle braces for tennis support sliding", volume: "950/mo", kd: "17%", intent: "Commercial" },
    { keyword: "tennis core rotation force measurement", volume: "140/mo", kd: "5%", intent: "Informational" },
    { keyword: "how wind shifts tennis ball bounce clay", volume: "180/mo", kd: "7%", intent: "Informational" },
    { keyword: "tennis dynamic stance recovery time frame", volume: "130/mo", kd: "4%", intent: "Informational" },
    { keyword: "WTA court slides mechanics research paper", volume: "90/mo", kd: "2%", intent: "Informational" },
    { keyword: "tennis foot wear wear rate comparison", volume: "310/mo", kd: "9%", intent: "Commercial" }
  ],
  "strategic-analysis-hockey-penalty-corner-dragflick": [
    { keyword: "penalty corner drag flick stick composite", volume: "520/mo", kd: "11%", intent: "Commercial" },
    { keyword: "sports field hockey penalty corner rules", volume: "850/mo", kd: "14%", intent: "Informational" },
    { keyword: "drag flick velocity calculation composite bow", volume: "190/mo", kd: "6%", intent: "Informational" },
    { keyword: "hockey first runner defense mask specs", volume: "330/mo", kd: "10%", intent: "Commercial" },
    { keyword: "field hockey drag flick training tutorial", volume: "450/mo", kd: "12%", intent: "Commercial" },
    { keyword: "olympic field hockey drag flick scoring rate", volume: "280/mo", kd: "9%", intent: "Informational" },
    { keyword: "field hockey drag flick hip rotation torque", volume: "140/mo", kd: "4%", intent: "Informational" },
    { keyword: "fih hockey drag flick stick bow limits", volume: "210/mo", kd: "7%", intent: "Informational" },
    { keyword: "compistes hockey stick bow bending calculation", volume: "110/mo", kd: "2%", intent: "Informational" },
    { keyword: "field hockey goalkeeper penalty corner positioning", volume: "390/mo", kd: "8%", intent: "Informational" },
    { keyword: "drag flick delivery speed ball lift angle", volume: "130/mo", kd: "3%", intent: "Informational" },
    { keyword: "how to defend penalty corners field hockey", volume: "430/mo", kd: "10%", intent: "Informational" },
    { keyword: "field hockey penalty corner stopper rules", volume: "310/mo", kd: "6%", intent: "Informational" },
    { keyword: "dragflick wrist release drills composite stick", volume: "250/mo", kd: "9%", intent: "Commercial" },
    { keyword: "field hockey composite vs wood drag flick", volume: "320/mo", kd: "8%", intent: "Investigational" },
    { keyword: "best hockey stick for drag flicking list", volume: "1150/mo", kd: "18%", intent: "Commercial" },
    { keyword: "hockey dynamic stance drag flick velocity", volume: "160/mo", kd: "5%", intent: "Informational" },
    { keyword: "field hockey defensive runner protective gear", volume: "680/mo", kd: "11%", intent: "Commercial" },
    { keyword: "drag flick slingshot potential energy physics", volume: "120/mo", kd: "4%", intent: "Informational" },
    { keyword: "field hockey ball velocity record dragflick", volume: "410/mo", kd: "7%", intent: "Informational" },
    { keyword: "how fast must first runner sprint hockey", volume: "150/mo", kd: "3%", intent: "Informational" },
    { keyword: "olympic field hockey coaching badges cost", volume: "490/mo", kd: "13%", intent: "Commercial" },
    { keyword: "field hockey penalty corner offensive plays", volume: "550/mo", kd: "11%", intent: "Informational" },
    { keyword: "dragflick biomechanics kinetic chain analysis", volume: "180/mo", kd: "5%", intent: "Informational" },
    { keyword: "field hockey training rebound boards online", volume: "750/mo", kd: "15%", intent: "Commercial" },
    { keyword: "hockey player back muscles dragflick injury", volume: "290/mo", kd: "8%", intent: "Informational" },
    { keyword: "how to get drag flick speed 120kmh", volume: "380/mo", kd: "12%", intent: "Informational" },
    { keyword: "field hockey penalty corner runner mask cheap", volume: "950/mo", kd: "16%", intent: "Commercial" },
    { keyword: "fih pro league tactical scoreboards live", volume: "980/mo", kd: "17%", intent: "Navigational" },
    { keyword: "field hockey scoop rule versus dragflick", volume: "230/mo", kd: "6%", intent: "Informational" },
    { keyword: "field hockey sticks size guide dragflick", volume: "850/mo", kd: "14%", intent: "Commercial" },
    { keyword: "lower back muscles physical exercises hockey", volume: "440/mo", kd: "9%", intent: "Commercial" },
    { keyword: "field hockey sticks bow placement comparison", volume: "520/mo", kd: "13%", intent: "Investigational" },
    { keyword: "penalty corner score prediction statistical models", volume: "110/mo", kd: "3%", intent: "Informational" },
    { keyword: "field hockey telemetry software clubs cost", volume: "270/mo", kd: "10%", intent: "Commercial" },
    { keyword: "dragflick release window timing milliseconds", volume: "120/mo", kd: "4%", intent: "Informational" },
    { keyword: "field hockey sweep hit vs dragflick", volume: "350/mo", kd: "9%", intent: "Informational" },
    { keyword: "field hockey penalty corner circle dimension meters", volume: "170/mo", kd: "5%", intent: "Informational" },
    { keyword: "best hockey cleats for wet turf grip", volume: "1100/mo", kd: "18%", intent: "Commercial" },
    { keyword: "hockey drag flicking practice goal boards", volume: "210/mo", kd: "8%", intent: "Commercial" },
    { keyword: "coaching hockey set play penalty corner video", volume: "480/mo", kd: "11%", intent: "Commercial" },
    { keyword: "composite sticks carbon percentage dragflick test", volume: "190/mo", kd: "7%", intent: "Informational" },
    { keyword: "dragflick shoulder rotation physical drills", volume: "220/mo", kd: "6%", intent: "Commercial" },
    { keyword: "penalty corner first runner run path meters", volume: "90/mo", kd: "2%", intent: "Informational" },
    { keyword: "hockey penalty card suspensions rules easy", volume: "620/mo", kd: "12%", intent: "Informational" },
    { keyword: "field hockey masks for corners safety comparison", volume: "750/mo", kd: "15%", intent: "Commercial" },
    { keyword: "field hockey goalkeeping padded kit cost", volume: "1350/mo", kd: "19%", intent: "Commercial" },
    { keyword: "dragflick progressive scoop action steps", volume: "140/mo", kd: "4%", intent: "Informational" },
    { keyword: "synthetic turf rolling resistance coefficient hockey", volume: "110/mo", kd: "5%", intent: "Informational" },
    { keyword: "composite hockey sports equipment shops", volume: "310/mo", kd: "10%", intent: "Commercial" }
  ],
  "rotational-mechanics-volleyball-serve-aerodynamics-float-jump": [
    { keyword: "hybrid float serve volleyball tutorial", volume: "680/mo", kd: "12%", intent: "Commercial" },
    { keyword: "karman vortex street volleyball aerodynamics", volume: "190/mo", kd: "5%", intent: "Informational" },
    { keyword: "magnus effect topspin jump serve volleyball", volume: "450/mo", kd: "10%", intent: "Informational" },
    { keyword: "how to hit a non spinning volleyball", volume: "390/mo", kd: "7%", intent: "Informational" },
    { keyword: "volleyball pass platform cushion stance tutorial", volume: "410/mo", kd: "9%", intent: "Commercial" },
    { keyword: "turbulent boundary layer separation ball sports", volume: "120/mo", kd: "3%", intent: "Informational" },
    { keyword: "fivb volleyball serving rules hybrid contact", volume: "320/mo", kd: "8%", intent: "Informational" },
    { keyword: "physics of non spinning volleyball flow", volume: "110/mo", kd: "2%", intent: "Informational" },
    { keyword: "underhand serve vs hybrid float serve volleyball", volume: "280/mo", kd: "6%", intent: "Informational" },
    { keyword: "volleyball serve speed measurement radars online", volume: "510/mo", kd: "11%", intent: "Commercial" },
    { keyword: "volleyball passing defensive forearms positioning", volume: "350/mo", kd: "8%", intent: "Informational" },
    { keyword: "volleyball ball seam design drag coefficient", volume: "180/mo", kd: "5%", intent: "Informational" },
    { keyword: "jump serve strike hand wrap mechanical steps", volume: "240/mo", kd: "7%", intent: "Informational" },
    { keyword: "hybrid volleyball float serve strike palm angle", volume: "140/mo", kd: "4%", intent: "Informational" },
    { keyword: "how to predict a float serve trajectory", volume: "330/mo", kd: "9%", intent: "Informational" },
    { keyword: "volleyball serves tracking camera software app", volume: "160/mo", kd: "6%", intent: "Commercial" },
    { keyword: "indoor volleyball serving drill plans coaching", volume: "620/mo", kd: "12%", intent: "Commercial" },
    { keyword: "wrist snapshot topspin jump serve tutorial", volume: "480/mo", kd: "11%", intent: "Commercial" },
    { keyword: "fivb tournament volleyball serving statistics live", volume: "850/mo", kd: "15%", intent: "Navigational" },
    { keyword: "volleyball shoulder cuff flexibility routine players", volume: "550/mo", kd: "10%", intent: "Commercial" },
    { keyword: "how to receive a float serve volleyball", volume: "750/mo", kd: "13%", intent: "Informational" },
    { keyword: "volleyball serve air density altitude changes", volume: "150/mo", kd: "6%", intent: "Informational" },
    { keyword: "best volleyballs for float serves coaching feedback", volume: "950/mo", kd: "17%", intent: "Commercial" },
    { keyword: "topspin force vector calculation ball serves", volume: "90/mo", kd: "2%", intent: "Informational" },
    { keyword: "volleyball training equipment rebounder nets cheap", volume: "1100/mo", kd: "18%", intent: "Commercial" },
    { keyword: "shoulder joint injury serve rotation volleyball", volume: "290/mo", kd: "8%", intent: "Informational" },
    { keyword: "improve volleyball overhead hit velocity runs", volume: "380/mo", kd: "11%", intent: "Commercial" },
    { keyword: "why float serves are harder to receive than power", volume: "440/mo", kd: "11%", intent: "Informational" },
    { keyword: "volleyball serve trajectory analysis simulators online", volume: "230/mo", kd: "10%", intent: "Commercial" },
    { keyword: "strike ball center of mass serve tutorial", volume: "170/mo", kd: "5%", intent: "Informational" },
    { keyword: "volleyball court measurements layout lines specifications", volume: "1250/mo", kd: "19%", intent: "Informational" },
    { keyword: "how to increase jump height volleyball training", volume: "1350/mo", kd: "18%", intent: "Commercial" },
    { keyword: "volleyball floor defensive stance balance metrics", volume: "130/mo", kd: "4%", intent: "Informational" },
    { keyword: "composite composite leather volleyballs rules brand", volume: "520/mo", kd: "13%", intent: "Investigational" },
    { keyword: "rotational mechanics volleyball hitting coaching certificate", volume: "270/mo", kd: "9%", intent: "Commercial" },
    { keyword: "volleyball hybrid serve risk percentage calculation", volume: "120/mo", kd: "4%", intent: "Informational" },
    { keyword: "volleyball player forearm skin bruises recovery tips", volume: "210/mo", kd: "7%", intent: "Informational" },
    { keyword: "how wind drafts affect float serves in sports centres", volume: "140/mo", kd: "3%", intent: "Informational" },
    { keyword: "WVL pro volleyball tour rosters live broadcast", volume: "680/mo", kd: "16%", intent: "Navigational" },
    { keyword: "topspin jump serve hand wrapping friction tutorial", volume: "190/mo", kd: "8%", intent: "Informational" },
    { keyword: "volleyball serving speed limits record index fivb", volume: "310/mo", kd: "7%", intent: "Informational" },
    { keyword: "hand stiffness index impact serve velocity volleyball", volume: "120/mo", kd: "5%", intent: "Informational" },
    { keyword: "how to block topspin serve trajectory early", volume: "250/mo", kd: "8%", intent: "Informational" },
    { keyword: "karman vortex lines CFD air simulation code", volume: "150/mo", kd: "6%", intent: "Informational" },
    { keyword: "best volleyball kneepads under 20 dollars list", volume: "1150/mo", kd: "14%", intent: "Commercial" },
    { keyword: "volleyball serving stance footing transition drills", volume: "420/mo", kd: "10%", intent: "Commercial" },
    { keyword: "volleyball jump serving footwork three step guide", volume: "360/mo", kd: "9%", intent: "Informational" },
    { keyword: "volleyball pass target landing zone calculations", volume: "110/mo", kd: "4%", intent: "Informational" },
    { keyword: "volleyball sports training agility cone maps online", volume: "390/mo", kd: "10%", intent: "Commercial" },
    { keyword: "fluid dynamic drag formula round sphere rotation", volume: "160/mo", kd: "5%", intent: "Informational" }
  ]
};
